package com.apibridge.generated.backend.resource;

import com.fasterxml.jackson.databind.JsonNode;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import com.apibridge.core.IntegrationProxy;

<#if flags.enableTelemetry>
import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.context.Scope;
</#if>

/**
 * Concrete, Quarkus native JAX-RS Resource generated by ApiBridge.
 * Fully compatible with Quarkus Reactive Rest and GraalVM Native Image compilation (AOT-ready).
 */
@Path("${basePath}")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class ${id?replace("-", " ")?capitalize?replace(" ", "")}Resource {

    private final IntegrationProxy integrationProxy;

    <#if flags.enableTelemetry>
    private static final Tracer tracer = GlobalOpenTelemetry.getTracer("apibridge-generator", "1.0.0");
    </#if>

    public ${id?replace("-", " ")?capitalize?replace(" ", "")}Resource(IntegrationProxy integrationProxy) {
        this.integrationProxy = integrationProxy;
    }

    <#list endpoints as endpoint>
    /**
     * Proxies incoming JAX-RS requests dynamically to downstream backend: ${endpoint.backendUrl}
     */
    @${endpoint.method?upper_case}
    @Path("${endpoint.path}")
    public Response handle${endpoint.telemetryName?replace("_", " ")?capitalize?replace(" ", "")}(JsonNode requestBody) {
        <#if flags.enableTelemetry>
        Span span = tracer.spanBuilder("${endpoint.telemetryName}")
                .setAttribute("http.method", "${endpoint.method?upper_case}")
                .setAttribute("http.url", "${endpoint.backendUrl}")
                .startSpan();
        
        try (Scope scope = span.makeCurrent()) {
            JsonNode response = integrationProxy.execute("${endpoint.backendUrl}", "${endpoint.method?upper_case}", requestBody);
            return Response.ok(response).build();
        } catch (Exception e) {
            span.recordException(e);
            span.setAttribute("error", true);
            throw e;
        } finally {
            span.end();
        }
        <#else>
        JsonNode response = integrationProxy.execute("${endpoint.backendUrl}", "${endpoint.method?upper_case}", requestBody);
        return Response.ok(response).build();
        </#if>
    }
    </#list>
}
