package com.apibridge.generated.backend.controller;

import com.fasterxml.jackson.databind.JsonNode;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import com.apibridge.core.IntegrationProxy;

<#if flags.enableTelemetry>
import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.context.Scope;
</#if>

/**
 * Concrete, Spring Boot native Controller generated by ApiBridge.
 * Fully compatible with Spring Boot 3 and GraalVM Native Image compilation (AOT-ready).
 */
@RestController
@RequestMapping("${basePath}")
public class ${id?replace("-", " ")?capitalize?replace(" ", "")}Controller {

    private final IntegrationProxy integrationProxy;

    <#if flags.enableTelemetry>
    private static final Tracer tracer = GlobalOpenTelemetry.getTracer("apibridge-generator", "1.0.0");
    </#if>

    public ${id?replace("-", " ")?capitalize?replace(" ", "")}Controller(IntegrationProxy integrationProxy) {
        this.integrationProxy = integrationProxy;
    }

    <#list endpoints as endpoint>
    /**
     * Proxies incoming API requests dynamically to downstream backend: ${endpoint.backendUrl}
     */
    @RequestMapping(
        value = "${endpoint.path}",
        method = RequestMethod.${endpoint.method?upper_case},
        consumes = "application/json",
        produces = "application/json"
    )
    public ResponseEntity<JsonNode> handle${endpoint.telemetryName?replace("_", " ")?capitalize?replace(" ", "")}(@RequestBody JsonNode requestBody) {
        <#if flags.enableTelemetry>
        Span span = tracer.spanBuilder("${endpoint.telemetryName}")
                .setAttribute("http.method", "${endpoint.method?upper_case}")
                .setAttribute("http.url", "${endpoint.backendUrl}")
                .startSpan();
        
        try (Scope scope = span.makeCurrent()) {
            JsonNode response = integrationProxy.execute("${endpoint.backendUrl}", "${endpoint.method?upper_case}", requestBody);
            return ResponseEntity.ok(response);
        } catch (Exception e) {
            span.recordException(e);
            span.setAttribute("error", true);
            throw e;
        } finally {
            span.end();
        }
        <#else>
        JsonNode response = integrationProxy.execute("${endpoint.backendUrl}", "${endpoint.method?upper_case}", requestBody);
        return ResponseEntity.ok(response);
        </#if>
    }
    </#list>
}
